config/routes.rb
Rails.application.routes.draw do

  root 'messages#index'
  resources :messages
  get 'messages/received' => 'messages#received'
  get 'messages/sent' => 'messages#sent'
  # post '/' => 'messages#create'
  # resources :messages

  resources :users

  resources :sessions, only: [:new, :create, :destroy]
  # get 'register', to: 'user#new', as: 'new'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  

  delete 'logout' => 'sessions#destroy'



  resources :friendships
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessor :recipient_identifier

  belongs_to :sender, class_name: "User", foreign_key: :sender_id
  belongs_to :recipient, class_name: "User", foreign_key: :recipient_id
  # has_many :sent_messages, foreign_key: "sender_id", class_name: "Message"
  # has_many :received_messages, foreign_key: "recipient_id", class_name: "Message"

  validates(:recipient_identifier, presence: true, :if => "recipient_id.nil?")
  validates(:subject, presence: true, length: 1..30)
  validates(:message, presence: true)

  before_save :set_recipient #
  default_scope { order('created_at DESC') }
  
	def read?
		!!read_at
	end
	
	# def sent_messages
	# 	Message.where(sender_id: id)
	# end

	# def received_messages
	# 	Message
	# end

  def remove_user(user)
    self.removed_by_sender = true if user == sender
    self.removed_by_recipient = true if user == recipient
    if removed_by_sender && removed_by_recipient
      self.destroy
    else
      self.save
    end
  end

  def valid_user?(user)
    (sender == user && !removed_by_sender) || (recipient == user && !removed_by_recipient)
  end

private

  def set_recipient
    if recipient_identifier
      recipient = User.find_by_identifier(recipient_identifier)
      self.recipient_id = recipient.try(:id)
    end
    false unless self.recipient_id
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_login
  before_action :set_message, only: [:show, :destroy]
  before_action :correct_users?, only: [:show, :destroy]

  def index
    populate_messages #gathers received, sent messages of the user
    prep_new_message #creates Message.new
  end

  def received
    session[:active_tab] = 'received'
    redirect_to messages_path
  end

  def sent
    session[:active_tab] = 'sent'
    redirect_to messages_path
  end

  def show
    @message.update_attribute(:read, true) if @message.recipient == current_user
  end

  def new
    session[:active_tab] = 'new'
    redirect_to messages_path(params[:recipient], recipient: params[:subject])
    # redirect_to messages_path(recipient: params[:recipient], recipient: params[:subject])
  end

  def create
    @users = User.all
    @message = current_user.sent_messages.build(message_params)
    return_to = session.delete(:return_to)
    if @message.save
      session[:active_tab] = 'sent'
      flash[:success] = "Message sent."
      # track_activity @message, [@message.recipient, @message.sender]
      redirect_to messages_path
    else
      session[:message] = message_params
      session[:active_tab] = 'new'
      flash.now[:error] = "Message failed to send." if @message.valid?
      populate_messages if params[:page] == "index"
      if params[:page]
        render params.delete(:page)
      else
        redirect_to messages_path #:back
      end
    end
  end

  def destroy
    # session[:active_tab] = @message.recipient == current_user ? 'received' : 'sent'
    # @message = Message.find_by_id(message.id) #DOESN'T WORK
    # @message = Message.find(params[:id]) #DOESN'T WORK
    @message.id = message.id #DOESN'T WORK
    @message.destroy #DOESN'T WORK
    # @message.remove_user(current_user) #DOESN'T WORK
    respond_to do |format|
      format.html do
        flash[:success] = "Message deleted."
        redirect_to messages_path
      end
      format.js do
      end
    end
  end

private

  def message_params
    params.require(:message).permit(:recipient_id, :subject, :message)#:recipient_identifier, 
  end

  def set_message
    @message = Message.find(params[:id])
  end

  def correct_users?
    validate_users(@message.recipient, @message.sender)
  end

  def prep_new_message
    if session[:message]
      @message = Message.new(session.delete(:message))
    elsif params[:recipient]
      recipient = params[:recipient]
      @message = Message.new(recipient_identifier: recipient)
    else
      @message = Message.new
    end
  end

  def populate_messages
    @received_messages = current_user.received_messages.includes(:sender).where(removed_by_recipient: false).paginate(page: params[:received_messages_page])
    @sent_messages = current_user.sent_messages.includes(:recipient).where(removed_by_sender: false).paginate(page: params[:sent_messages_page])
    @active_tab = session.delete(:active_tab) ||  params.delete(:active_tab) || "received"
  end

##########
  def validate_users(*users)
    unless valid_users?(*users)
      flash[:error] = "Unauthorized to access that content."
      redirect_to root_path
    end
  end

  def valid_users?(*users)
    users.any? { |user| current_user? user }
  end

  def current_user?(user)
    user == current_user
  end

  def sign_in(user)
    self.current_user = user
  end

  def sign_out
    self.current_user = nil
  end

  def signed_in?
    !current_user.nil?
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def current_user=(user)
    @current_user = user
  end

  # def current_user
  #   @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  # end

  def current_user?(user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end

  def valid_users?(*users)
    users.any? { |user| current_user? user }
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_fields.html.haml
= f.association :recipient, label_method: :username, value_method: :id

/ = f.association :recipient, label_method: :email, value_method: :id

/= f.select :recipient_id, User.collect{|e| [e.email, e.id]}, {}, class: 'form-control'

/ = debug options_for_select(User.all.map({|e| [e.email, e.id]})

= f.input :subject

= f.input :message, as: :text

= f.submit "Send Message", class: "btn btn-primary btn-block"

app/views/messages/_received_message.html.haml
Received

= content_tag :tr, id: "message_#{message.id}" do
  %td= message.id
  %td= message.sender.nil? ? "Deleted" : (link_to message.sender.username, message.sender)
  %td= link_to message.subject, message
  %td= link_to (message.read ? "Read" : "Unread"), message
  %td= message.created_at.strftime("%m/%d/%Y %I:%M %p")
  %td= link_to '&times'.html_safe, message_path(message.id), method: :delete, type: 'button', class: 'close', remote: true, data: {confirm: "Are you sure?"}
  

app/views/messages/_sent_message.html.haml
Sent

= content_tag :tr, id: "message_#{message.id}" do

  %td= message.id
  %td= message.recipient.nil? ? "Deleted" : (link_to message.recipient.username, message.recipient)
  %td= link_to message.subject, message
  %td= link_to (message.read ? "Read" : "Unread"), message
  %td= link_to '&times;'.html_safe, message_path(message.id), method: :delete, type: 'button', class: 'close', remote: true
  /s%td= format_time message.created_at
  

app/views/messages/index.html.haml
.container.row
  %h3 SnapChat! Messages Home
  %form.form-inline.pull-xs-right	

  / = render 'layouts/search'

  / = form_tag :controller => 'messages', :action => 'index', :method => 'get' do
  /   = text_field_tag :search, params[:search]
  /     %button.btn.btn-success-outline{:type => "submit"} Search

%ul#message_tabs.nav.nav-tabs
  = content_tag :li, class: (@active_tab == "received" ? "active" : "") do
    %a{href: "#received_tab", data: {toggle: "tab"}} Received
  = content_tag :li, class: (@active_tab == 'sent' ? "active" : "") do
    %a{href: "#sent_tab", data: {toggle: 'tab'}} Sent
  %li
    = link_to "New", new_message_path
  / = content_tag :li, class: (@active_tab == 'new' ? "active" : "") do
  /   %a{href: "#new_tab", data: {toggle: 'tab'}} New


.tab-content
  = content_tag :div, id: "received_tab", class: "tab-pane#{' active' if @active_tab == 'received'}" do
    %br
    %table.table.table-hover
      %thead
        %tr
          %th ID
          %th Sender
          %th Subject
          %th{width: '5%'} Read?
          %th{width: '20%'} Date Sent
          %th{width: '5%'} Delete?
      %tbody
        - if @received_messages.blank?
          %tr
            %td No messages found.
        - else
          = render partial: 'received_message', collection: @received_messages, as: :message
    / .pull-right
    /   = will_paginate @received_messages, param_name: :received_messages_page, params: {active_tab: 'received'}
    .clearfix

  = content_tag :div, id: "sent_tab", class: "tab-pane#{' active' if @active_tab == 'sent'}" do
    %br
    %table.table.table-hover
      %thead
        %tr
          %th ID
          %th Recipient
          %th Subject
          %th{width: '5%'} Read?
          %th{width: '20%'} Date Sent
          %th{width: '5%'} Delete?
      %tbody
        - if @sent_messages.blank?
          %tr
            %td No messages found.
        - else
          = render partial: 'sent_message', collection: @sent_messages, as: :message
    / .pull-right
    /   = will_paginate @sent_messages, param_name: :sent_messages_page, params: {active_tab: 'sent'}
    .clearfix

  = content_tag :div, id: "new_tab", class: "tab-pane#{' active' if @active_tab == 'new'}" do
    %br
    .col-sm-8.col-sm-offset-2
      = simple_form_for @message, html: { role: "form" } do |f|
        %input{name: "page", type: "hidden", value: "index"}
        = render 'fields', f: f
    .clearfix

app/views/messages/new.html.haml
%h3 New Message



= f.input :message, as: :text

= f.submit "Send Message", class: "btn btn-primary btn-block"

app/views/messages/show.html.haml
%h3 Message
= @message.subject

.card
  %p= simple_format @message.message 
//, sanitize: true