config/routes.rb
Rails.application.routes.draw do

  root 'messages#index'
  resources :messages
  get 'messages/received' => 'messages#received'
  get 'messages/sent' => 'messages#sent'
  # post '/' => 'messages#create'
  # resources :messages

  resources :users

  resources :sessions, only: [:new, :create, :destroy]
  # get 'register', to: 'user#new', as: 'new'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  

  delete 'logout' => 'sessions#destroy'



  resources :friendships
end

app/models/user.rb
# require 'carrierwave/orm/activerecord'
# require 'bcrypt'

class User < ActiveRecord::Base
  has_secure_password
 #attr_accessor :new_password, :new_password_confirmation, :password, :avatar 
	
  #AVATAR
  mount_uploader :avatar, AvatarUploader
  has_many :avatars
  accepts_nested_attributes_for :avatars

  #EMAIL VALIDATIONS
  validates(:username, presence: true)
  # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates(:email, presence: true) #format: { with: VALID_EMAIL_REGEX })
  validates_uniqueness_of :email, case_sensitive: false

  #FRIENDSHIPS
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: :friend_id, dependent: :destroy
  has_many :inverse_friends, through: :inverse_friendships, source: :user

  #MESSAGES
  has_many :sent_messages, class_name: "Message", foreign_key: :sender_id
  has_many :received_messages, class_name: "Message", foreign_key: :recipient_id

  def unread_message_count
    received_messages.where(read: false).count
  end
  
  def self.find_by_identifier(identifier)
    User.where("lower(username) = ?", identifier.downcase).first ||
      User.where("lower(email) = ?", identifier.downcase).first
  end

  def self.purge_unconfirmed(num)
    User.unscoped.where(confirmed: false).where("updated_at < ?", num.days.ago).destroy_all
  end

  #FACEBOOK
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :correct_users?, only: [:edit, :update, :destroy]

	def index
		# @users = User.all
		# User.all :conditions => (current_user ? ["id != ?", current_user.id] : [])
		@users = User.where("id != ?", current_user.id)
	end

	def new
		# sign_out unless current_user
		@user = User.new
		render :layout => false 
	end	

	def create
		@user = User.create user_params
		# @user = User.new(user_params)

		if @user.persisted?

		# if @user.save
			# UserMailer.user_confirmation_email(@user).deliver
			session[:user_id] = @user.id
			flash[:success] = 'Registered!'
			redirect_to login_path
		else
			flash.now[:error] = "#{@user.errors.full_messages.to_sentence}"
			render 'new'
		end
	end


	def show
		@user = User.find(params[:id])
	end

	private
		def user_params
			params.require(:user).permit(:recipient_id, :username, :email, :password, :password_confirmation, :avatar) #, :password_confirmation, :new_password, :new_password_confirmation, :password_confirmation
		end

def hash_new_password
    unhashed_password = new_password || password
     unless unhashed_password.blank?
       self.hashed_password = BCrypt::Password.create(unhashed_password)
     end
  end
end

app/helpers/users_helper.rb
module UsersHelper

	# def flash_class_name(key)
	# 	case key.to_s
	# 	when "success"
	# 		"alert-success"
	# 	when "error"
	# 		"alert-danger"
	# 	when "warning"
	# 		"alert-warning"
	# 	end
	# end
  # def signed_in?
  #   !current_user.nil?
  # end

  # def flash_class_name(key)
  # 	case key.to_s
  # 	when 'success'
  # 		"alert-success"
  # 	when 'error'
  # 	else
  # 		"alert-warning"
  # 	end
  # end
end

app/views/users/_user_sm.html.haml
.container
  .row
    .col-sm-10
      %h1 #{friend.username}
    .col-sm-2
      .pull-right
        / = image_tag(@user.avatar_url, :size => "200", :class => "img-responsive")
        / = image_tag @user.avatar_url(:square300), class: "img-responsive"

:javascript
  $(document).ready(function(){
    (function vendorTableSorter(){ 
      /* paste all the vendor code here */
    }());
  });// end document.ready

app/views/users/index.html.haml
%h1 Users Index
- @users.each do |user|
	.card
		%a{:href => "/users/#{user.id}"} #{user.username} 
		= link_to "Add Friend", friendships_path(friend_id: user), method: :post, class: "btn btn-success" #(friend_id: user)
		= link_to "Send a Message", new_message_path, class: "btn btn-success"

app/views/users/new.html.haml
!!!
%html{lang: "en"}
	%head
		%title
			CoderSnap

	%body
		- flash.each do |name, msg|
			%div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
				.container
					= msg

		.container
			.col-md-6
				%h3
					Register User
					
				= simple_form_for @user do |f|
					= f.input :username, class: "form-control"
					= f.input :email, class: "form-control"
					= f.input :password, as: :password, label: "Password"
					= f.input :password_confirmation, as: :password, label: "Confirm Password"
					= f.file_field :avatar
					= f.submit

				.additional-links
					By signing up you agree to
					%a{:href => "#"} Terms of Use
					and
					%a{:href => "#"} Privacy

= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
= javascript_include_tag 'application', 'data-turbolinks-track' => true
= csrf_meta_tags


:css
	body { 
	background: url('http://res.cloudinary.com/nara/image/upload/v1458308288/laptopgirl_gj3axq.jpg') no-repeat center center fixed; 
	-webkit-background-size: cover;
	-moz-background-size: cover;
	-o-background-size: cover;
	background-size: cover;
	}

/= f.input :password, class: "form-control"

app/views/users/show.html.haml
.container
  .row
    .col-sm-10
      %h1 #{@user.username}
    .col-sm-2
      .pull-right
        / = image_tag(@user.avatar_url, :size => "200", :class => "img-responsive")
        = image_tag @user.avatar_url(:square300), class: "img-responsive"

:javascript
  $(document).ready(function(){
    (function vendorTableSorter(){ 
      /* paste all the vendor code here */
    }());
  });// end document.ready