config/routes.rb
Rails.application.routes.draw do

  root 'messages#index'
  resources :messages
  get 'messages/received' => 'messages#received'
  get 'messages/sent' => 'messages#sent'
  # post '/' => 'messages#create'
  # resources :messages

  resources :users

  resources :sessions, only: [:new, :create, :destroy]
  # get 'register', to: 'user#new', as: 'new'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  

  delete 'logout' => 'sessions#destroy'



  resources :friendships
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  #skip_before_action :require_login#, only: [:create, :index, :destroy, :friend_requests]
  before_action :friend_requests #set_friendship, only: [:show, :edit, :update, :destroy]

  def create
    @friendship = current_user.friendships.build(friend_id: params[:friend_id])
    @valid = @friendship.save
    respond_to do |format|
      format.html do
        if @valid
          flash[:success] = "Friended."#{@friendship.friend.username} 
        else
          flash[:error] = "Unable to add friend."
        end
        redirect_to :back
      end
      format.js do
        if current_user.mutual_friends.include? @friendship.friend
          @new_friend = @friendship.friend
          inverse_friendship = current_user.inverse_friendships.where(user: @friendship.friend).first
        end
      end
    end
  end

  def destroy
    @friendship = current_user.friendships.find_by_friend_id(params[:id])
    @inverse_friendship = current_user.inverse_friendships.find_by_user_id(params[:id])
    friend = User.find(params[:id])
    message = "Unfriended #{ friend.username }."

    begin
      @friendship.destroy
    rescue
      message = "Rejected #{ friend.username }'s friend request."
    end
    begin
      @inverse_friendship.destroy
    rescue
      message = "Cancelled your friend request to #{ friend.username }."
    end

    respond_to do |format|
      format.html do
        flash[:success] = message
        redirect_to :back
      end
      format.js do
      end
    end
  end

  def index
    # @search_form = params.has_key?(:search_form) ? SearchForm.new(search_params) : SearchForm.new
    @active_tab = params.delete(:active_tab) || session.delete(:active_tab) || 'mutual'
    @mutual = mutual_friends
    @requests = friend_requests
    @pending = pending_friends
    #unless @search_form.search_for.blank?
      # @mutual = @mutual.where(
      #   "lower(username) LIKE lower(?)",
      #   "#{Regexp.escape(@search_form.search_for)}%"
      # )
      # @requests = @requests.where(
      #   "lower(username) LIKE lower(?)",
      #   "#{Regexp.escape(@search_form.search_for)}%"
      # )
      # @pending = @pending.where(
      #   "lower(username) LIKE lower(?)",
      #   "#{Regexp.escape(@search_form.search_for)}%"
      # )
    # end
    respond_to do |format|
      format.html do
        @mutual = @mutual.paginate(page: params[:mutual_page])
        @requests = @requests.paginate(page: params[:requests_page])
        @pending = @pending.paginate(page: params[:pending_page])
      end
      format.js do
        @mutual = @mutual.paginate(page: nil)
        @requests = @requests.paginate(page: nil)
        @pending = @pending.paginate(page: nil)
        render 'friends'
      end
    end
  end
  

  # private
  #   def set_friendship
  #     @friendship = Friendship.find(params[:id])
  #   end

  #   def friendship_params
  #     params.fetch(:friendship, {})
  #   end

# ##### SESSIONS DEFINITIONS

    def validate_users(*users)
      unless valid_users?(*users)
      flash[:error] = "Unauthorized to access that content."
      redirect_to root_path
      end
    end

    def valid_users?(*users)
      users.any? { |user| current_user? user }
    end

    def current_user?(user)
      user == current_user
    end

    def sign_in(user)
      self.current_user = user
    end

    def sign_out
      self.current_user = nil
    end

    def signed_in?
      !current_user.nil?
    end

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    # def current_user=(user)
    #   @current_user = user
    # end

    # def current_user
    #   @current_user ||= User.find_by_id(params[:id])
    # end

    def current_user?(user)
      user == current_user
    end

    def redirect_back_or(default)
      redirect_to(session[:return_to] || default)
      session.delete(:return_to)
    end

    def store_location
      session[:return_to] = request.url
    end

    def valid_users?(*users)
      users.any? { |user| current_user? user }
    end

    def validate_users(*users)
      unless valid_users?(*users)
        flash[:error] = "Unauthorized to access that content."
        redirect_to root_path
      end
    end

# ######## FRIENDSHIPS DEFINITIONS

    def friends
      session[:active_tab] = 'mutual'
      redirect_to friendships_path
    end

  def friend_request?(friendship)
    inverse = Friendship.where(friend: friendship.user, user: friendship.friend)
    if inverse.count == 0 || inverse.first.created_at > friendship.created_at
      true
    else
      false
    end
  end

    def requests
      session[:active_tab] = 'requests'
      redirect_to friendships_path
    end

    def pending
      session[:active_tab] = 'pending'
      redirect_to friendships_path
    end

    def mutual_friends
      current_user.friends.where(id: current_user.inverse_friends.map { |inverse| inverse.id })
    end

    def mutual_friendships
      current_user.friendships.where(friend_id: current_user.inverse_friendships.map { |inverse| inverse.user_id })
    end

    def pending_friends
      current_user.friends.where.not(id: current_user.inverse_friends.map { |inverse| inverse.id})
    end

    def friend_requests
      current_user.inverse_friends.where.not(id: current_user.friends.map { |friend| friend.id})
    end

    def friend_request_count
      request_total = current_user.inverse_friends.count #- mutual_friends.count
    end

end

app/views/friendships/_friend.html.haml
%tr
  %td= link_to friend.username, friend
  %td
    .pull-right
      = link_to new_message_path(recipient: friend.username), class: "btn btn-sm btn-primary" do
        %span.glyphicon.glyphicon-envelope
        Message

app/views/friendships/_friendships.html.haml
.panel.panel-default
  .panel-heading
    = link_to friend do
      = content_tag :h3, friend.username, class: "panel-title"
  .panel-body
    .container
      .row
        = render 'users/user_sm', friend: friend
      .row
        .btn-group.pull-right
          = link_to "Message", new_message_path(recipient: friend.username), class: "btn btn-primary"
          = link_to "Unfriend", friendship_path(friend), method: :delete, class: 'btn btn-danger'

/ #myModal.modal.fade{ role: 'dialog', aria: {hidden: true}}
/   .modal-dialog
/     .modal-content
/       .modal-header
/         %button.close{data: {dismiss: "modal"}, aria: {hidden: true}} &times;
/         = content_tag :h4, "Disconnect from #{friend.username}", class: 'modal-title'
/       .modal-body
/         = content_tag :p, "Are you sure you would like to remove #{friend.username} from your network?"
/       .modal-footer
/         = link_to "Unlink", friendship_path(friend), method: :delete, class: "btn btn-primary"
/         %button.btn.btn-default{data: {dismiss: "modal"}} Cancel


/ #myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
/   .modal-dialog{:role => "document"}
/     .modal-content
/       .modal-header
/         %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
/           %span{"aria-hidden" => "true"} &times;
/         %h4#myModalLabel.modal-title Modal title
/       .modal-body
/         \...
/       .modal-footer
/         %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Close
/         %button.btn.btn-primary{:type => "button"} Save changes

app/views/friendships/_list.html.haml
- if friends.empty?
  You don't have any friends in your network
- else
  %table#home_friends.table
    - friends.each do |friend|
      = render 'friendships/friend', friend: friend

app/views/friendships/_pending.html.haml
.panel.panel-default
  .panel-heading
    = link_to friend do
      = content_tag :h3, friend.username, class: "panel-title"
  .panel-body
    .container
      .row
        = render 'users/user_sm', friend: friend
      .row
        .btn-group.pull-right
          = link_to "Message", new_message_path(recipient: friend.username), class: "btn btn-primary"
          = link_to 'Cancel Request', friendship_path(friend), method: :delete, class: 'btn btn-danger'


.modal.fade{id: "cancel_modal_#{friend.id}", role: 'dialog', aria: {hidden: true}}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{data: {dismiss: "modal"}, aria: {hidden: true}} &times;
        = content_tag :h4, "Cancel request to #{friend.username}", class: 'modal-title'
      .modal-body
        = content_tag :p, "Are you sure you would like to cancel your network request to #{friend.username}?"
      .modal-footer
        = link_to "Cancel Request", friendship_path(friend), method: :delete, class: "btn btn-primary"
        %button.btn.btn-default{data: {dismiss: "modal"}} Maintain Request

app/views/friendships/_pendings.html.haml
= render partial: 'pending', collection: pending, as: :friend
.pull-right
  = will_paginate pending, param_name: :pending_page, params: {active_tab: "pending"}

app/views/friendships/_request.html.haml
.panel.panel-default
  .panel-heading
    = link_to user do
      = content_tag :h3, user.username, class: "panel-title"
  .panel-body
    .container
      .row
        = render 'users/user_sm', friend: user
      .row
        .btn-group.pull-right
          = link_to "Message", new_message_path(recipient: user.username), class: "btn btn-primary"
          = link_to 'Approve', friendships_path(user_id: user), method: :post, type: 'button', class: 'btn btn-success'
          / = link_to 'Reject', "#reject_modal_#{user.id}", type: 'button', class: 'btn btn-danger', data: {toggle: 'modal'}
          = link_to "Reject", friendship_path(user), method: :delete, class: 'btn btn-danger'

/ .modal.fade{id: "reject_modal_#{user.id}", role: 'dialog', aria: {hidden: true}}
/   .modal-dialog
/     .modal-content
/       .modal-header
/         %button.close{data: {dismiss: "modal"}, aria: {hidden: true}} &times;
/         = content_tag :h4, "Reject #{user.username}", class: 'modal-title'
/       .modal-body
/         = content_tag :p, "Are you sure you would like to reject #{user.username}'s request?"
/       .modal-footer
/         = link_to "Reject", friendship_path(user), method: :delete, class: "btn btn-primary"
/         %button.btn.btn-default{data: {dismiss: "modal"}} Cancel

app/views/friendships/_requests.html.haml
= render partial: 'request', collection: requests, as: :user
.pull-right
  = will_paginate requests, param_name: :requests_page, params: {active_tab: "requests"}

app/views/friendships/edit.html.haml
%h1 Editing friendship

= render 'form'

= link_to 'Show', @friendship
\|
= link_to 'Back', friendships_path

app/views/friendships/index.html.haml
.row
  %h1.col-sm-8.col-md-9 Friends
  / = render 'layouts/search', url: friendships_path

%ul#friendship_tabs.nav.nav-tabs
  = content_tag :li, class: (@active_tab == "mutual" ? "active" : "") do
    %a{href: "#mutual", data: {toggle: "tab"}} Current Friends
  = content_tag :li, class: (@active_tab == "requests" ? "active" : "") do
    %a{href: "#requests", data: {toggle: "tab"}} These Want To Be Your Friend
  = content_tag :li, class: (@active_tab == "pending" ? "active" : "") do
    %a{href: "#pending", data: {toggle: "tab"}} You Sent Friend Requests To These

.tab-content
  = content_tag :div, id: 'mutual', class: "tab-pane#{' active' if @active_tab == 'mutual'}" do
    %br
    - if @mutual.blank?
      %h2 No network
    - else
      .mutual.searchable
        - @mutual.each do |friend|
          = render 'friendships', friend: friend

  = content_tag :div, id: 'requests', class: "tab-pane#{' active' if @active_tab == 'requests'}" do
    %br
    - if @requests.blank?
      %h2 No one is awaiting approval from you
    - else
      .requests.searchable
        = render 'requests', requests: @requests

  = content_tag :div, id: 'pending', class: "tab-pane#{' active' if @active_tab == 'pending'}" do
    %br
    - if @pending.blank?
      %h2 You are not awaiting approval from anyone
    - else
      .pending.searchable
        = render 'pendings', pending: @pending

app/views/friendships/new.html.haml
%h1 New friendship

= render 'form'

= link_to 'Back', friendships_path

app/views/friendships/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_friendship_path(@friendship)
\|
= link_to 'Back', friendships_path