config/routes.rb
Rails.application.routes.draw do

  root 'messages#index'
  resources :messages
  get 'messages/received' => 'messages#received'
  get 'messages/sent' => 'messages#sent'
  # post '/' => 'messages#create'
  # resources :messages

  resources :users

  resources :sessions, only: [:new, :create, :destroy]
  # get 'register', to: 'user#new', as: 'new'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  

  delete 'logout' => 'sessions#destroy'



  resources :friendships
end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-light.bg-faded
  %button.navbar-toggler.hidden-sm-up{"data-target" => "#exCollapsingNavbar2", "data-toggle" => "collapse", :type => "button"}
    ☰
  #exCollapsingNavbar2.collapse.navbar-toggleable-xs
    %ul.nav.navbar-nav
      %li.nav-item.active
        %a.nav-link{:href => "/"} Home
      / %li.nav-item
      /   %a.nav-link{:href => "/messages"} Messages
      %li.nav-item
        %a.nav-link{:href => friendships_path} Friends
      %li.nav-item
        %a.nav-link{:href => "/users"} Add Friends
      / %li.nav-item
      /   %a.nav-link{:href => "http://learning.coderschool.vn/courses/ruby_on_rails/unit/2#!assignment"} About
      %li.nav-item
        - if current_user
          Welcome #{current_user.username}
          %li.nav-item
            = link_to "Logout", logout_path #, nethod: 'delete'
        - else
          = link_to "Login", login_path #, nethod: 'delete'
          %li.nav-item
            = link_to "Register", new_user_path


- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    .container
      = msg

/ - flash.each do |key, value|
/   = content_tag(:div, class: "alert alert-#{key}") do
/     = value

app/views/layouts/_search.html.haml
.container
  = form_for @search_form, url: url, method: :get, class: "form col-sm-4 col-md-3", role: "form", remote: true do |f|
    .input-group
      = f.text_field :search_for, class: "form-control", autofocus: true
      %span.input-group-addon.glyphicon.glyphicon-search

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %title
      SnapChat!

  %body
    #wrap
    = render 'layouts/header'

    .container

      = yield

    .fb-like{"data-share" => "true", "data-show-faces" => "true", "data-width" => "450"}

  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

:javascript
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '585884868229980',
      xfbml      : true,
      version    : 'v2.5'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));